import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Generates CSS variable files from the canonical tokens.json (v1.1).
 *
 * Source: apps/web/src/tokens/source/tokens.json (vendored from
 *   wiki/design-system/tokens.json).
 *
 * Output:
 *   - tokens.css                 :root { type, scale, lh, space, radius,
 *                                motion, density-default, z, accent-h,
 *                                user-mark, light theme colors,
 *                                focus, color-scheme: light }
 *                                + html[data-density="compact"]
 *                                + html[data-radius="sharp" | "soft"]
 *   - theme-default-dark.css     html.dark { color overrides, focus, color-scheme: dark }
 *   - agent-palette.css          :root { --agent-1..6 light }
 *                                + html.dark { --agent-1..6 dark }
 *
 * Light is the default theme; the dark theme is applied by toggling
 * the `dark` class on <html>. The two modifier blocks (density, radius
 * preset) live in tokens.css so they're always available regardless of
 * theme.
 *
 * CI runs the generator + git diff --exit-code on the generated dir,
 * so any drift between source and generated fails the build.
 */

interface TypeScale {
  '2xs': string
  xs: string
  sm: string
  md: string
  lg: string
  xl: string
  '2xl': string
  '3xl': string
}

interface LineHeights {
  tight: number
  snug: number
  prose: number
}

interface DensityBlock {
  'row-h': string
  'pad-x': string
  'pad-y': string
}

interface RadiusPreset {
  '1': string
  '2': string
  '3': string
  '4': string
}

interface NeutralBlock {
  bg: string
  'bg-elev': string
  'bg-sunk': string
  'bg-hover': string
  line: string
  'line-soft': string
  'line-strong': string
  text: string
  'text-2': string
  'text-3': string
  'text-4': string
}

interface AccentBlock {
  base: string
  strong: string
  soft: string
  ink: string
  on: string
}

interface SemanticBlock {
  danger: string
  'danger-soft': string
  warn: string
  'warn-soft': string
  info: string
  'info-soft': string
}

interface ShadowBlock {
  '1': string
  '2': string
  pop: string
}

interface ThemeBlock {
  colorScheme: 'light' | 'dark'
  neutral: NeutralBlock
  accent: AccentBlock
  semantic: SemanticBlock
  shadow: ShadowBlock
  focus: string
}

export interface Tokens {
  $schema?: string
  version: string
  description?: string
  naming?: unknown
  type: {
    family: { sans: string; mono: string }
    scale: TypeScale
    lh: LineHeights
  }
  space: Record<string, string>
  radius: { '1': string; '2': string; '3': string; '4': string; pill: string }
  radiusPresets: { sharp: RadiusPreset; soft: RadiusPreset }
  motion: {
    ease: string
    duration: { fast: string; normal: string; slow: string }
  }
  density: { default: DensityBlock; compact: DensityBlock }
  z: Record<string, number>
  accent: { h: number; rule?: string }
  agentHues: { description?: string; light: string[]; dark: string[] }
  userMark: { from: string; to: string; rule: string }
  themes: { light: ThemeBlock; dark: ThemeBlock }
}

export interface GeneratedFiles {
  'tokens.css': string
  'theme-default-dark.css': string
  'agent-palette.css': string
}

const HEADER = '/* Auto-generated by apps/web/scripts/generate-tokens.ts. Do not edit by hand. */'

function header(note: string, version: string): string[] {
  return [HEADER, `/* Source: apps/web/src/tokens/source/tokens.json (${note}, v${version}) */`, '']
}

function emitNeutral(n: NeutralBlock, indent = '  '): string[] {
  return [
    `${indent}--bg: ${n.bg};`,
    `${indent}--bg-elev: ${n['bg-elev']};`,
    `${indent}--bg-sunk: ${n['bg-sunk']};`,
    `${indent}--bg-hover: ${n['bg-hover']};`,
    `${indent}--line: ${n.line};`,
    `${indent}--line-soft: ${n['line-soft']};`,
    `${indent}--line-strong: ${n['line-strong']};`,
    `${indent}--text: ${n.text};`,
    `${indent}--text-2: ${n['text-2']};`,
    `${indent}--text-3: ${n['text-3']};`,
    `${indent}--text-4: ${n['text-4']};`,
  ]
}

function emitAccent(a: AccentBlock, indent = '  '): string[] {
  return [
    `${indent}--accent: ${a.base};`,
    `${indent}--accent-strong: ${a.strong};`,
    `${indent}--accent-soft: ${a.soft};`,
    `${indent}--accent-ink: ${a.ink};`,
    `${indent}--on-accent: ${a.on};`,
  ]
}

function emitSemantic(s: SemanticBlock, indent = '  '): string[] {
  return [
    `${indent}--danger: ${s.danger};`,
    `${indent}--danger-soft: ${s['danger-soft']};`,
    `${indent}--warn: ${s.warn};`,
    `${indent}--warn-soft: ${s['warn-soft']};`,
    `${indent}--info: ${s.info};`,
    `${indent}--info-soft: ${s['info-soft']};`,
  ]
}

function emitShadow(sh: ShadowBlock, indent = '  '): string[] {
  return [
    `${indent}--shadow-1: ${sh['1']};`,
    `${indent}--shadow-2: ${sh['2']};`,
    `${indent}--shadow-pop: ${sh.pop};`,
  ]
}

export function generateBaseTokens(t: Tokens): string {
  const lines: string[] = []
  lines.push(...header('type, space, radius, motion, density, light theme defaults', t.version))
  lines.push(':root {')
  lines.push('  /* Type */')
  lines.push(`  --ds-font-sans: ${t.type.family.sans};`)
  lines.push(`  --ds-font-mono: ${t.type.family.mono};`)
  lines.push('')
  for (const [k, v] of Object.entries(t.type.scale) as [string, string][]) {
    lines.push(`  --ds-text-${k}: ${v};`)
  }
  lines.push('')
  lines.push(`  --ds-lh-tight: ${String(t.type.lh.tight)};`)
  lines.push(`  --ds-lh-snug: ${String(t.type.lh.snug)};`)
  lines.push(`  --ds-lh-prose: ${String(t.type.lh.prose)};`)
  lines.push('')

  lines.push('  /* Space */')
  for (const [k, v] of Object.entries(t.space)) {
    lines.push(`  --ds-${k}: ${v};`)
  }
  lines.push('')

  lines.push('  /* Radius */')
  lines.push(`  --ds-r-1: ${t.radius['1']};`)
  lines.push(`  --ds-r-2: ${t.radius['2']};`)
  lines.push(`  --ds-r-3: ${t.radius['3']};`)
  lines.push(`  --ds-r-4: ${t.radius['4']};`)
  lines.push(`  --ds-r-pill: ${t.radius.pill};`)
  lines.push('')

  lines.push('  /* Motion */')
  lines.push(`  --ds-ease: ${t.motion.ease};`)
  lines.push(`  --ds-dur-fast: ${t.motion.duration.fast};`)
  lines.push(`  --ds-dur: ${t.motion.duration.normal};`)
  lines.push(`  --ds-dur-slow: ${t.motion.duration.slow};`)
  lines.push('')

  lines.push('  /* Density (default) */')
  lines.push(`  --ds-row-h: ${t.density.default['row-h']};`)
  lines.push(`  --ds-pad-x: ${t.density.default['pad-x']};`)
  lines.push(`  --ds-pad-y: ${t.density.default['pad-y']};`)
  lines.push('')

  lines.push('  /* Z-index */')
  for (const [k, v] of Object.entries(t.z)) {
    lines.push(`  --z-${k}: ${String(v)};`)
  }
  lines.push('')

  lines.push('  /* Accent hue (single integer drives every accent shade) */')
  lines.push(`  --accent-h: ${String(t.accent.h)};`)
  lines.push('')

  lines.push('  /* User mark */')
  lines.push(`  --user-c-from: ${t.userMark.from};`)
  lines.push(`  --user-c-to: ${t.userMark.to};`)
  lines.push('')

  lines.push('  /* Light theme — neutrals */')
  lines.push(...emitNeutral(t.themes.light.neutral))
  lines.push('')
  lines.push('  /* Light theme — accent (derived from --accent-h) */')
  lines.push(...emitAccent(t.themes.light.accent))
  lines.push('')
  lines.push('  /* Light theme — semantic */')
  lines.push(...emitSemantic(t.themes.light.semantic))
  lines.push('')
  lines.push('  /* Light theme — shadow */')
  lines.push(...emitShadow(t.themes.light.shadow))
  lines.push('')
  lines.push(`  --focus: ${t.themes.light.focus};`)
  lines.push('')
  lines.push(`  color-scheme: ${t.themes.light.colorScheme};`)
  lines.push('}')
  lines.push('')

  lines.push('/* Density modifier — compact */')
  lines.push('html[data-density="compact"] {')
  lines.push(`  --ds-row-h: ${t.density.compact['row-h']};`)
  lines.push(`  --ds-pad-x: ${t.density.compact['pad-x']};`)
  lines.push(`  --ds-pad-y: ${t.density.compact['pad-y']};`)
  lines.push('}')
  lines.push('')

  lines.push('/* Radius preset — sharp */')
  lines.push('html[data-radius="sharp"] {')
  lines.push(`  --ds-r-1: ${t.radiusPresets.sharp['1']};`)
  lines.push(`  --ds-r-2: ${t.radiusPresets.sharp['2']};`)
  lines.push(`  --ds-r-3: ${t.radiusPresets.sharp['3']};`)
  lines.push(`  --ds-r-4: ${t.radiusPresets.sharp['4']};`)
  lines.push('}')
  lines.push('')

  lines.push('/* Radius preset — soft */')
  lines.push('html[data-radius="soft"] {')
  lines.push(`  --ds-r-1: ${t.radiusPresets.soft['1']};`)
  lines.push(`  --ds-r-2: ${t.radiusPresets.soft['2']};`)
  lines.push(`  --ds-r-3: ${t.radiusPresets.soft['3']};`)
  lines.push(`  --ds-r-4: ${t.radiusPresets.soft['4']};`)
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

export function generateDarkTheme(t: Tokens): string {
  const lines: string[] = []
  lines.push(...header('themes.dark', t.version))
  lines.push('html.dark {')
  lines.push('  /* Neutrals */')
  lines.push(...emitNeutral(t.themes.dark.neutral))
  lines.push('')
  lines.push('  /* Accent (derived from --accent-h) */')
  lines.push(...emitAccent(t.themes.dark.accent))
  lines.push('')
  lines.push('  /* Semantic */')
  lines.push(...emitSemantic(t.themes.dark.semantic))
  lines.push('')
  lines.push('  /* Shadow */')
  lines.push(...emitShadow(t.themes.dark.shadow))
  lines.push('')
  lines.push(`  --focus: ${t.themes.dark.focus};`)
  lines.push('')
  lines.push(`  color-scheme: ${t.themes.dark.colorScheme};`)
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

export function generateAgentPalette(t: Tokens): string {
  const lines: string[] = []
  lines.push(...header('agentHues', t.version))
  if (t.agentHues.description) {
    lines.push(`/* ${t.agentHues.description} */`)
    lines.push('')
  }
  lines.push(':root {')
  t.agentHues.light.forEach((color, i) => {
    lines.push(`  --agent-${String(i + 1)}: ${color};`)
  })
  lines.push('}')
  lines.push('')
  lines.push('html.dark {')
  t.agentHues.dark.forEach((color, i) => {
    lines.push(`  --agent-${String(i + 1)}: ${color};`)
  })
  lines.push('}')
  lines.push('')
  lines.push('/* Class-based mapping: agent name hashes to one of these slots; */')
  lines.push('/* the class sets --agent-color so component CSS reads it uniformly. */')
  for (let i = 0; i < t.agentHues.light.length; i += 1) {
    lines.push(`.agent-c${String(i)} { --agent-color: var(--agent-${String(i + 1)}); }`)
  }
  lines.push('')
  return lines.join('\n')
}

export function generateAll(t: Tokens): GeneratedFiles {
  return {
    'tokens.css': generateBaseTokens(t),
    'theme-default-dark.css': generateDarkTheme(t),
    'agent-palette.css': generateAgentPalette(t),
  }
}

function isMain(): boolean {
  if (!process.argv[1]) return false
  const calledScript = path.resolve(process.argv[1])
  const thisScript = fileURLToPath(import.meta.url)
  return calledScript === thisScript
}

if (isMain()) {
  const thisDir = path.dirname(fileURLToPath(import.meta.url))
  const sourcePath = path.resolve(thisDir, '../src/tokens/source/tokens.json')
  const outDir = path.resolve(thisDir, '../src/tokens/generated')

  const raw = fs.readFileSync(sourcePath, 'utf-8')
  const tokens = JSON.parse(raw) as Tokens

  const generated = generateAll(tokens)

  fs.mkdirSync(outDir, { recursive: true })

  // Remove any pre-v1.1 generated files (theme-default-light.css no
  // longer exists; light is in :root). Drift protection in CI relies
  // on the generated dir matching exactly what the generator emits.
  const obsolete = ['theme-default-light.css']
  for (const name of obsolete) {
    const p = path.join(outDir, name)
    if (fs.existsSync(p)) fs.unlinkSync(p)
  }

  const entries = Object.entries(generated) as [keyof GeneratedFiles, string][]
  for (const [filename, content] of entries) {
    fs.writeFileSync(path.join(outDir, filename), content, 'utf-8')
  }

  console.log(
    `Generated ${String(entries.length)} CSS files in ${path.relative(process.cwd(), outDir)}`,
  )
  for (const [filename] of entries) {
    console.log(`  ${filename}`)
  }
}
