import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Generates CSS variable files from the canonical tokens.json.
 *
 * Source: apps/web/src/tokens/source/tokens.json (vendored copy of
 *   wiki/design-system/tokens.json).
 *
 * Output: apps/web/src/tokens/generated/
 *   - tokens.css                 :root { type, space, radius, border,
 *                                duration, ease, z, user-mark }
 *   - theme-default-dark.css     .theme-dark { color, shadow }
 *   - theme-default-light.css    .theme-light { color, shadow }
 *   - agent-palette.css          .agent-c0 ... .agent-c11 { --agent-color }
 *
 * The generator is also invoked at predev + prebuild time so the
 * generated files are always fresh; CI runs the generator and fails
 * on any drift between source and generated.
 */

interface TypeScale {
  size: string
  track: string
  weight: number
  lh: number
}

interface ThemeBlock {
  color: Record<string, string>
  shadow: Record<string, string>
}

export interface Tokens {
  $schema?: string
  version: string
  description?: string
  type: {
    fontFamily: { sans: string; mono: string }
    scale: Record<string, TypeScale>
  }
  space: Record<string, string>
  radius: Record<string, string>
  border: Record<string, string>
  duration: Record<string, string>
  ease: Record<string, string>
  z: Record<string, number>
  agentPalette: { description: string; colors: string[] }
  userMark: { from: string; to: string; rule: string }
  themes: {
    dark: ThemeBlock
    light: ThemeBlock
  }
}

export interface GeneratedFiles {
  'tokens.css': string
  'theme-default-dark.css': string
  'theme-default-light.css': string
  'agent-palette.css': string
}

const HEADER = '/* Auto-generated by apps/web/scripts/generate-tokens.ts. Do not edit by hand. */'

function header(sourceNote: string, version: string): string[] {
  return [
    HEADER,
    `/* Source: apps/web/src/tokens/source/tokens.json ${sourceNote} (v${version}) */`,
    '',
  ]
}

export function generateBaseTokens(t: Tokens): string {
  const lines: string[] = []
  lines.push(...header('(type, space, radius, border, duration, ease, z, user-mark)', t.version))
  lines.push(':root {')
  lines.push(`  --type-family-sans: ${t.type.fontFamily.sans};`)
  lines.push(`  --type-family-mono: ${t.type.fontFamily.mono};`)
  lines.push('')

  for (const [name, scale] of Object.entries(t.type.scale)) {
    lines.push(`  --type-${name}-size: ${scale.size};`)
    lines.push(`  --type-${name}-track: ${scale.track};`)
    lines.push(`  --type-${name}-weight: ${String(scale.weight)};`)
    lines.push(`  --type-${name}-lh: ${String(scale.lh)};`)
  }
  lines.push('')

  for (const [k, v] of Object.entries(t.space)) lines.push(`  --space-${k}: ${v};`)
  lines.push('')

  for (const [k, v] of Object.entries(t.radius)) lines.push(`  --radius-${k}: ${v};`)
  lines.push('')

  for (const [k, v] of Object.entries(t.border)) lines.push(`  --border-${k}: ${v};`)
  lines.push('')

  for (const [k, v] of Object.entries(t.duration)) lines.push(`  --duration-${k}: ${v};`)
  lines.push('')

  for (const [k, v] of Object.entries(t.ease)) lines.push(`  --ease-${k}: ${v};`)
  lines.push('')

  for (const [k, v] of Object.entries(t.z)) lines.push(`  --z-${k}: ${String(v)};`)
  lines.push('')

  lines.push(`  --user-c-from: ${t.userMark.from};`)
  lines.push(`  --user-c-to: ${t.userMark.to};`)
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

export function generateThemeColor(themeName: 'dark' | 'light', t: Tokens): string {
  const themeData = t.themes[themeName]
  const lines: string[] = []
  lines.push(...header(`themes.${themeName}`, t.version))
  lines.push(`.theme-${themeName} {`)

  for (const [k, v] of Object.entries(themeData.color)) {
    lines.push(`  --color-${k}: ${v};`)
  }
  lines.push('')

  for (const [k, v] of Object.entries(themeData.shadow)) {
    lines.push(`  --shadow-${k}: ${v};`)
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

export function generateAgentPalette(t: Tokens): string {
  const lines: string[] = []
  lines.push(...header('agentPalette', t.version))
  lines.push(`/* ${t.agentPalette.description} */`)
  lines.push('')

  t.agentPalette.colors.forEach((color, i) => {
    lines.push(`.agent-c${String(i)} {`)
    lines.push(`  --agent-color: ${color};`)
    lines.push('}')
    if (i !== t.agentPalette.colors.length - 1) lines.push('')
  })
  lines.push('')

  return lines.join('\n')
}

export function generateAll(t: Tokens): GeneratedFiles {
  return {
    'tokens.css': generateBaseTokens(t),
    'theme-default-dark.css': generateThemeColor('dark', t),
    'theme-default-light.css': generateThemeColor('light', t),
    'agent-palette.css': generateAgentPalette(t),
  }
}

function isMain(): boolean {
  if (!process.argv[1]) return false
  const calledScript = path.resolve(process.argv[1])
  const thisScript = fileURLToPath(import.meta.url)
  return calledScript === thisScript
}

if (isMain()) {
  const thisDir = path.dirname(fileURLToPath(import.meta.url))
  const sourcePath = path.resolve(thisDir, '../src/tokens/source/tokens.json')
  const outDir = path.resolve(thisDir, '../src/tokens/generated')

  const raw = fs.readFileSync(sourcePath, 'utf-8')
  const tokens = JSON.parse(raw) as Tokens

  const generated = generateAll(tokens)

  fs.mkdirSync(outDir, { recursive: true })
  const entries = Object.entries(generated) as [keyof GeneratedFiles, string][]
  for (const [filename, content] of entries) {
    fs.writeFileSync(path.join(outDir, filename), content, 'utf-8')
  }

  console.log(
    `Generated ${String(entries.length)} CSS files in ${path.relative(process.cwd(), outDir)}`,
  )
  for (const [filename] of entries) {
    console.log(`  ${filename}`)
  }
}
