import { describe, expect, it } from 'vitest'
import {
  generateAgentPalette,
  generateAll,
  generateBaseTokens,
  generateThemeColor,
  type Tokens,
} from '../scripts/generate-tokens'

const minimalFixture: Tokens = {
  version: '0.3.0',
  type: {
    fontFamily: {
      sans: 'Inter, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    scale: {
      body: { size: '13px', track: '-0.005em', weight: 400, lh: 1.45 },
      label: { size: '11px', track: '0.10em', weight: 500, lh: 1.4 },
    },
  },
  space: { '1': '4px', '4': '16px' },
  radius: { sm: '3px', lg: '8px' },
  border: { default: '1px', emphasis: '2px' },
  duration: { fast: '120ms', slow: '280ms' },
  ease: { out: 'cubic-bezier(0.2, 0.7, 0.2, 1)' },
  z: { base: 0, modal: 500 },
  agentPalette: {
    description: '12-color deterministic palette.',
    colors: ['oklch(0.66 0.13 25)', 'oklch(0.70 0.13 55)', 'oklch(0.78 0.13 85)'],
  },
  userMark: {
    from: 'oklch(0.65 0.10 280)',
    to: 'oklch(0.55 0.12 200)',
    rule: 'Never reuse an agent color.',
  },
  themes: {
    dark: {
      color: { 'bg-primary': 'oklch(0.16 0.005 250)', 'text-primary': 'oklch(0.97 0.003 250)' },
      shadow: { 'elevation-1': '0 1px 2px black' },
    },
    light: {
      color: { 'bg-primary': 'oklch(0.985 0.002 90)', 'text-primary': 'oklch(0.18 0.005 250)' },
      shadow: { 'elevation-1': '0 1px 2px gray' },
    },
  },
}

describe('generateBaseTokens', () => {
  const css = generateBaseTokens(minimalFixture)

  it('opens with the auto-generated header', () => {
    expect(css).toMatch(/Auto-generated by apps\/web\/scripts\/generate-tokens\.ts/)
    expect(css).toMatch(/v0\.3\.0/)
  })

  it('emits a :root block', () => {
    expect(css).toContain(':root {')
    expect(css).toContain('}')
  })

  it('includes type families', () => {
    expect(css).toContain('--type-family-sans: Inter, sans-serif;')
    expect(css).toContain('--type-family-mono: JetBrains Mono, monospace;')
  })

  it('flattens type-scale fields', () => {
    expect(css).toContain('--type-body-size: 13px;')
    expect(css).toContain('--type-body-track: -0.005em;')
    expect(css).toContain('--type-body-weight: 400;')
    expect(css).toContain('--type-body-lh: 1.45;')
    expect(css).toContain('--type-label-size: 11px;')
  })

  it('emits space, radius, border, duration, ease, z tokens', () => {
    expect(css).toContain('--space-1: 4px;')
    expect(css).toContain('--space-4: 16px;')
    expect(css).toContain('--radius-sm: 3px;')
    expect(css).toContain('--border-default: 1px;')
    expect(css).toContain('--duration-fast: 120ms;')
    expect(css).toContain('--ease-out: cubic-bezier(0.2, 0.7, 0.2, 1);')
    expect(css).toContain('--z-base: 0;')
    expect(css).toContain('--z-modal: 500;')
  })

  it('emits user-mark gradient endpoints', () => {
    expect(css).toContain('--user-c-from: oklch(0.65 0.10 280);')
    expect(css).toContain('--user-c-to: oklch(0.55 0.12 200);')
  })
})

describe('generateThemeColor', () => {
  it('emits a .theme-dark selector with color + shadow tokens', () => {
    const css = generateThemeColor('dark', minimalFixture)
    expect(css).toContain('.theme-dark {')
    expect(css).toContain('--color-bg-primary: oklch(0.16 0.005 250);')
    expect(css).toContain('--color-text-primary: oklch(0.97 0.003 250);')
    expect(css).toContain('--shadow-elevation-1: 0 1px 2px black;')
  })

  it('emits a .theme-light selector with the light values', () => {
    const css = generateThemeColor('light', minimalFixture)
    expect(css).toContain('.theme-light {')
    expect(css).toContain('--color-bg-primary: oklch(0.985 0.002 90);')
    expect(css).toContain('--shadow-elevation-1: 0 1px 2px gray;')
    expect(css).not.toContain('.theme-dark')
  })

  it('records the source theme block in the header', () => {
    const dark = generateThemeColor('dark', minimalFixture)
    const light = generateThemeColor('light', minimalFixture)
    expect(dark).toContain('themes.dark')
    expect(light).toContain('themes.light')
  })
})

describe('generateAgentPalette', () => {
  const css = generateAgentPalette(minimalFixture)

  it('emits one selector per palette entry, indexed from 0', () => {
    expect(css).toContain('.agent-c0 {')
    expect(css).toContain('--agent-color: oklch(0.66 0.13 25);')
    expect(css).toContain('.agent-c1 {')
    expect(css).toContain('--agent-color: oklch(0.70 0.13 55);')
    expect(css).toContain('.agent-c2 {')
    expect(css).toContain('--agent-color: oklch(0.78 0.13 85);')
  })

  it('does not emit a slot for a non-existent palette index', () => {
    expect(css).not.toContain('.agent-c3 ')
    expect(css).not.toContain('.agent-c11')
  })

  it('preserves the palette description as a comment', () => {
    expect(css).toContain('/* 12-color deterministic palette. */')
  })
})

describe('generateAll', () => {
  it('returns all four expected files', () => {
    const all = generateAll(minimalFixture)
    expect(Object.keys(all).sort()).toEqual([
      'agent-palette.css',
      'theme-default-dark.css',
      'theme-default-light.css',
      'tokens.css',
    ])
  })

  it('is deterministic: same input produces same output', () => {
    const a = generateAll(minimalFixture)
    const b = generateAll(minimalFixture)
    expect(a).toEqual(b)
  })
})
