/**
 * Fleet.md: shared agent roster auto-generated by the supervisor.
 *
 * Every agent on a 2200 install needs to know who else is on the
 * server and what each peer does, so a request that lands outside
 * an agent's lane can be routed to the right peer (Hobby asks Simon
 * for DevOps, etc.) without escalating to the human. This is also
 * the substrate for newly-spawned agents (David in the Cray test) to
 * orient on day one.
 *
 * Source of truth and lifecycle:
 *   - Generated from `<home>/state/supervisor.json` (membership +
 *     current state) joined with each agent's `identity.md` (role,
 *     model, handle) and `<home>/config/user.md` (the human).
 *   - Written to `<home>/state/fleet.md`.
 *   - Regenerated on agent create / start / stop, model picker save,
 *     and identity edits. Heartbeat-only updates that don't change
 *     any membership / role / model / status field are no-op writes
 *     (we compare content before writing).
 *
 * Consumers:
 *   - The agent loop reads it at the start of every task and injects
 *     it into the system prompt as a `## Fleet` block, so the LLM has
 *     the team context inline without a tool call.
 *   - The HTTP API exposes it at `GET /api/v1/fleet` for the Studio
 *     and CLI.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { HomePaths } from '../storage/layout.js'
import { loadIdentity } from '../identity/loader.js'
import { loadUserIdentityIfExists } from '../user/loader.js'
import { composeModelId } from '../identity/types.js'
import type { SupervisorState } from './types.js'
import { createLogger, type Logger } from '../util/logger.js'

export const FLEET_SCHEMA_VERSION = 1

export interface FleetAgentEntry {
  name: string
  display_name: string
  handle: string
  role: string
  model: string
  state: string
}

export interface FleetUserEntry {
  display_name: string
  handle: string
}

export interface FleetData {
  schema_version: typeof FLEET_SCHEMA_VERSION
  generated_at: string
  agents: FleetAgentEntry[]
  user: FleetUserEntry | null
}

export function fleetPath(home: string): string {
  return join(home, 'state', 'fleet.md')
}

/**
 * Read each agent's identity from disk and the user identity from
 * `<home>/config/user.md`, then assemble a FleetData snapshot.
 *
 * Identity-load failures are non-fatal: an agent whose identity file
 * cannot be read drops out of the roster (logged as a warning) but
 * the rest of the fleet still renders. This avoids a single
 * malformed identity blocking every other agent from learning the
 * fleet. The state snapshot is the source of truth for membership;
 * disk identities only fill in role/model.
 */
export async function buildFleetData(args: {
  home: string
  paths: HomePaths
  state: SupervisorState
  logger?: Logger
}): Promise<FleetData> {
  const log = args.logger ?? createLogger('supervisor/fleet')
  const agents: FleetAgentEntry[] = []
  for (const ag of Object.values(args.state.agents)) {
    try {
      const id = await loadIdentity(ag.identity_path)
      const fm = id.frontmatter
      agents.push({
        name: ag.name,
        display_name: fm.pub?.display_name ?? ag.name,
        handle: fm.pub?.handle ?? `@${ag.name}`,
        role: fm.agent_role,
        model: composeModelId(fm.model),
        state: ag.state,
      })
    } catch (err) {
      log.warn('fleet: agent identity unreadable; skipping', {
        name: ag.name,
        identity_path: ag.identity_path,
        error: err instanceof Error ? err.message : String(err),
      })
    }
  }
  // Sort by name for stable rendering.
  agents.sort((a, b) => a.name.localeCompare(b.name))

  let user: FleetUserEntry | null = null
  try {
    const u = await loadUserIdentityIfExists(args.paths.configUserMd)
    if (u) {
      user = {
        display_name: u.frontmatter.display_name,
        handle: u.frontmatter.pub.handle,
      }
    }
  } catch (err) {
    log.warn('fleet: user identity unreadable; rendering without operator', {
      error: err instanceof Error ? err.message : String(err),
    })
  }

  return {
    schema_version: FLEET_SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    agents,
    user,
  }
}

/**
 * Render a FleetData as a markdown document. The shape is stable so
 * agents can rely on a consistent layout in the system prompt.
 */
export function renderFleetMarkdown(data: FleetData): string {
  const lines: string[] = []
  lines.push('---')
  lines.push(`schema_version: ${String(data.schema_version)}`)
  lines.push(`generated_at: ${data.generated_at}`)
  lines.push('---')
  lines.push('')
  lines.push('# 2200 Fleet')
  lines.push('')
  lines.push(
    'The agents and humans on this 2200 install. Auto-regenerated by the supervisor. Use this to know who is on the team and who to route a task to. To address an agent in a pub, mention them with their handle (e.g. `@simon …`); the @-mention is the only way the runtime wakes a peer.',
  )
  lines.push('')
  if (data.user) {
    lines.push('## Operator (human)')
    lines.push('')
    lines.push(
      `- **${data.user.handle}** — ${data.user.display_name}. Owns product decisions; pinged when the team is genuinely blocked.`,
    )
    lines.push('')
  }
  if (data.agents.length === 0) {
    lines.push('## Agents')
    lines.push('')
    lines.push('_No agents registered on this install yet._')
    lines.push('')
  } else {
    lines.push('## Agents')
    lines.push('')
    for (const ag of data.agents) {
      lines.push(`### ${ag.handle} — ${ag.display_name}`)
      lines.push('')
      lines.push(`- **Role:** ${ag.role}`)
      lines.push(`- **Model:** \`${ag.model}\``)
      lines.push(`- **State:** ${ag.state}`)
      lines.push('')
    }
  }
  return lines.join('\n')
}

/**
 * Compose + write the fleet to disk. Skips the write when the
 * content is byte-identical to what's already there so heartbeat
 * churn doesn't constantly rewrite the file (and doesn't trigger
 * downstream re-reads on a no-op).
 *
 * Returns true when the file was actually written, false on no-op.
 */
export async function regenerateFleet(args: {
  home: string
  paths: HomePaths
  state: SupervisorState
  logger?: Logger
}): Promise<boolean> {
  const data = await buildFleetData(args)
  // The generated_at timestamp would always make content different,
  // so render a stable comparison string with the timestamp masked.
  const path = fleetPath(args.home)
  const next = renderFleetMarkdown(data)
  const nextStable = stripGeneratedAt(next)
  let prev: string | null = null
  try {
    prev = await readFile(path, 'utf8')
  } catch {
    prev = null
  }
  if (prev !== null && stripGeneratedAt(prev) === nextStable) {
    return false
  }
  await writeFile(path, next, { mode: 0o644 })
  args.logger?.info('fleet regenerated', {
    path,
    agents: data.agents.length,
    user: data.user ? data.user.handle : null,
  })
  return true
}

function stripGeneratedAt(md: string): string {
  return md.replace(/^generated_at:.*$/m, 'generated_at: <stable>')
}
