/**
 * Fleet doc viewer.
 *
 * Renders the supervisor-maintained Fleet.md so the operator can see
 * the same roster context the agents see in their system prompt.
 * Read-only at v1; the file is auto-regenerated by the supervisor on
 * agent / identity / model changes.
 */
import { type ReactElement } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ApiError, NetworkError, api } from '../../lib/api'
import { Card, ErrorState, LoadingState, Screen, ScreenNavLink } from '../../primitives'
import styles from './FleetDocScreen.module.css'

function formatError(err: unknown): string {
  if (err instanceof ApiError) return `${err.code}: ${err.message}`
  if (err instanceof NetworkError) return 'Cannot reach the runtime.'
  return err instanceof Error ? err.message : String(err)
}

export function FleetDocScreen(): ReactElement {
  const fleetQuery = useQuery({
    queryKey: ['fleet'],
    queryFn: () => api.fleet(),
    staleTime: 10_000,
    refetchInterval: 10_000,
  })

  return (
    <Screen
      crumbs={['2200', 'roster']}
      title="Fleet roster"
      lede="The agents and humans on this 2200 install. Auto-regenerated by the supervisor; injected into every agent's system prompt at task start."
      actions={<ScreenNavLink to="/">← Fleet</ScreenNavLink>}
    >
      {fleetQuery.isLoading ? (
        <Card padding={20}>
          <LoadingState rows={4} />
        </Card>
      ) : fleetQuery.isError ? (
        <Card padding={0}>
          <ErrorState title="Could not load fleet" body={formatError(fleetQuery.error)} />
        </Card>
      ) : (
        <>
          <Card padding={20}>
            <div className={styles.meta}>
              {fleetQuery.data?.path}
              {fleetQuery.data?.generated_at
                ? ` · regenerated ${fleetQuery.data.generated_at}`
                : ''}
            </div>
          </Card>
          <Card padding={20}>
            <div className={styles.markdown}>{fleetQuery.data?.markdown ?? ''}</div>
          </Card>
        </>
      )}
    </Screen>
  )
}
